---
- name: Automatisation de la création d'objets et de politiques sur FortiGate
  hosts: fortigate_1
  collections:
    - fortinet.fortios
  gather_facts: false
  # Transmet le token automatiquement à TOUS les modules de la collection Fortinet
  module_defaults:
    group/fortinet.fortios.fortios:
      access_token: "{{ fortios_access_token }}"
      vdom: "{{ vdom }}"

  tasks:
    # Step 1 : Création de l'objet Adresse Source
    - name: Créer l'objet Adresse Source (LAN Subnet)
      fortinet.fortios.fortios_firewall_address:
        state: "present"
        firewall_address:
          name: "OBJ_LAN_SUBNET"
          type: "ipmask"
          subnet: "192.168.10.0 255.255.255.0"
          comment: "Réseau LAN interne créé via Ansible"

    # Step 2 : Création de l'objet Adresse Destination
    - name: Créer l'objet Adresse Destination (Serveur Web)
      fortinet.fortios.fortios_firewall_address:
        state: "present"
        firewall_address:
          name: "OBJ_SERVEUR_WEB"
          type: "ipmask"
          subnet: "10.0.0.50 255.255.255.255"
          comment: "Serveur Web DMZ créé via Ansible"

    # Step 3 : Création de la Politique de Pare-feu
    - name: Créer la règle de politique de sécurité
      fortinet.fortios.fortios_firewall_policy:
        state: "present"
        firewall_policy:
          policyid: 0
          name: "ALLOW_LAN_TO_WEB_001"
          srcintf:
            - name: "port1"
          dstintf:
            - name: "port2"
          srcaddr:
            - name: "OBJ_LAN_SUBNET"
          dstaddr:
            - name: "OBJ_SERVEUR_WEB"
          service:
            - name: "HTTP"
            - name: "HTTPS"
          action: "accept"
          schedule: "always"
          nat: "enable"
          status: "enable"
          logtraffic: "all"
          comments: "Regle creee automatiquement par Ansible"